CREATE TABLE IF NOT EXISTS posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  issue INTEGER DEFAULT 1,   -- 第几期（可选）
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
